[tool.poetry]
name = "pykka"
version = "3.1.1"
description = "Pykka is a Python implementation of the actor model"
authors = ["Stein Magnus Jodal <stein.magnus@jodal.no>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/jodal/pykka"
repository = "https://github.com/jodal/pykka"
documentation = "https://pykka.readthedocs.io/"
keywords = ["actor", "concurrency", "threading"]
classifiers = [
   "Development Status :: 5 - Production/Stable",
   "Intended Audience :: Developers",
   "Topic :: Software Development :: Libraries",
]
include = ["docs", "examples", "tests"]

[tool.poetry.dependencies]
python = "^3.8.0"

[tool.poetry.group.dev.dependencies]
black = "^22.1"
flake8 = "^5.0.4"
flake8-black = "^0.3.3"
flake8-bugbear = "^22.9.23"
flake8-isort = "^4.2.0"
flake8-pyi = "^22.8.2"
isort = "^5.9.2"
mypy = "^0.971"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"
tox = "^4.5.2"

[tool.poetry.group.docs.dependencies]
sphinx = "^6.2.1"
sphinx_rtd_theme = "^1.2.1"
toml = "^0.10.2"

[tool.black]
target-version = ["py38", "py39", "py310", "py311"]

[tool.isort]
profile = "black"

[tool.mypy]
no_implicit_optional = true
strict_equality = true
warn_return_any = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true

[[tool.mypy.overrides]]
# Options that only applies to src, and not tests
module = "pykka.*"
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["pytest.*"]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
