name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: python -m pip install poetry==1.3.1 tox==4.0.17
      - run: tox --skip-missing-interpreters true
      - run: poetry build
      - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
